export const tea = [
  {
    id: 1,
    name: "Trà Dưa Đào Sung Túc",
    price: 58,
    salePrice: 40,
    img: "tra-dao-dua-luoi.jpg",
    cate: "tea",
    size: ["Vừa"],
    desc: "Vị thơm ngọt của Dưa lưới và đào tươi chua chua, ngọt ngọt trên nền trà Oolong trứ danh cùng lớp foam cheese mỏng nhẹ vị mặn mặn tạo nên sự cân bằng cho thức uống, sẽ đem đến cho bạn, gia đình và bạn bè những giai điệu tươi vui cho mùa xuân mới. ",
    story: [
      "Dưa Đào Sung Túc - Giai điệu tươi vui cho mùa xuân mới",
      "Trà Dưa Đào Sung Túc với vị thơm ngọt của Dưa lưới và đào tươi chua chua, ngọt ngọt trên nền trà Oolong trứ danh cùng lớp foam cheese mỏng nhẹ vị mặn mặn tạo nên sự cân bằng cho thức uống, sẽ đem đến cho bạn, gia đình và bạn bè những giai điệu tươi vui, thịnh vượng cho mùa xuân mới. Dưa Đào Sung Túc của The Coffee House sẽ là đại diện chúc cho năm mới khởi đầu đầy thuận lợi, các chiến hữu sẽ vẫn sát cánh bên nhau thật “sung”. Đặc biệt là đong đầy lộc lá và thật “son” trong năm mới. Cụng ly Dưa Đào Sung Túc của The Coffee House để không khí thêm rộn ràng, khởi đầu sung túc và rước lộc đầu năm bạn nhé!",
    ],
  },
  {
    id: 2,
    name: "Trà Sen Nhãn Sum Vầy",
    price: 58,
    salePrice: 40,
    img: "tra-sen-nhan.jpg",
    cate: "tea",
    size: ["Vừa"],
    desc: "Thức uống mang hương vị của nhãn, của sen, của trà Oolong đầy thanh mát cho tất cả các thành viên trong dịp Tết này. An lành, thư thái và đậm đà chính là những gì The Coffee House mong muốn gửi trao đến bạn và gia đình.",
    story: [
      "Sen Nhãn Sum Vầy - Cho Tết thêm trọn vẹn",
      "Được kết hợp bởi hạt sen thanh bùi, nhãn lồng ngọt mát, lớp foam cheese dịu dàng bên trên. Ly Trà Sen Nhãn Sum Vầy - Một hương vị đặc biệt cho Tết này The Coffee House dành tặng bạn. Một lời chúc KHỞI ĐẦU SUNG với thật nhiều ngày hò hẹn bên bạn bè, người thân sau một năm nhiều xa cách. ",
    ],
  },
  {
    id: 3,
    name: "Trà Hạt Sen Đá",
    price: 45,
    salePrice: 32,
    img: "tra-sen-da.jpg",
    cate: "tea",
    size: ["Nhỏ", "Vừa", "Lớn"],
    desc: "Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi, bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.",
    story: [
      "Trà hạt sen - Sự tinh tế của những điều đơn giản",
      "Trà Oolong - thảo dược quý giúp bạn bồi bổ sức khoẻ: Trong trà ô long có chứa rất nhiều vitamin, khoáng chất và những chất chống oxy hóa rất tốt. Hạt sen cung cấp một lượng lớn gluxit, lipit, canxi, chất xơ và các vitamin mang đến nhiều lợi ích ch người dùng từ tác dụng chống viêm, giúp an thần, đến công dụng đẹp da, chống lão hoá, điều hoà cholesterol và đường huyết.",
    ],
  },
  {
    id: 4,
    name: "Trà Hạt Sen Nóng",
    price: 51,
    salePrice: 36,
    img: "tra-sen-nong.jpg",
    cate: "tea",
    size: ["Vừa"],
    desc: "Nền trà oolong hảo hạng kết hợp cùng hạt sen tươi, bùi bùi và lớp foam cheese béo ngậy. Trà hạt sen là thức uống thanh mát, nhẹ nhàng phù hợp cho cả buổi sáng và chiều tối.",
    story: [
      "Trà hạt sen - Sự tinh tế của những điều đơn giản",
      "Trà Oolong - thảo dược quý giúp bạn bồi bổ sức khoẻ: Trong trà ô long có chứa rất nhiều vitamin, khoáng chất và những chất chống oxy hóa rất tốt. Hạt sen cung cấp một lượng lớn gluxit, lipit, canxi, chất xơ và các vitamin mang đến nhiều lợi ích ch người dùng từ tác dụng chống viêm, giúp an thần, đến công dụng đẹp da, chống lão hoá, điều hoà cholesterol và đường huyết.",
    ],
  },
  {
    id: 5,
    name: "Trà Long Nhãn Hạt Chia",
    price: 45,
    salePrice: 32,
    img: "nhan-hat-chia.png",
    cate: "tea",
    size: ["Nhỏ", "Vừa", "Lớn"],
    desc: "Quả Phúc Bồn Tử hoàn toàn tự nhiên, được các barista Nhà kết hợp một cách đầy tinh tế cùng trà Oolong và cam vàng tạo ra một dư vị hoàn toàn tươi mới. Mát lạnh ngay từ ngụm đầu tiên, đọng lại cuối cùng là hương vị trà thơm lừng và vị ngọt thanh, chua dịu khó quên của trái phúc bồn tử.",
    story: [
      "Trà Phúc Bồn Tử The Coffee House - Sự kết hợp đầy hoàn hảo giữa thanh mát và bổ dưỡng ",
      "Món trà phúc bồn tử với 2 nguyên liệu chính: quả phúc bồn tử tươi và trà oolong hảo hạng. Phúc bồn tử hay còn gọi là quả mâm xôi là một trong những loại quả rất được ưa chuộng bởi không những chỉ trông thôi đã muốn ăn ngay, mà bản thân nó còn mang lại nhiều giá trị sức khỏe đáng kinh ngạc. Quả Phúc Bồn Tử hoàn toàn tự nhiên, được các barista Nhà kết hợp một cách đầy tinh tế cùng trà Oolong hảo hạng và cam vàng tạo ra một dư vị hoàn toàn tươi mới. Mát lạnh ngay từ ngụm đầu tiên, đọng lại cuối cùng là hương vị trà thơm lừng và vị ngọt thanh, chua dịu khó quên của quả phúc bồn tử tươi.",
    ],
  },
  {
    id: 6,
    name: "Trà Đào Cam Sả Đá",
    price: 45,
    salePrice: 32,
    img: "tra-cam-sa-da.jpg",
    cate: "tea",
    size: ["Nhỏ", "Vừa", "Lớn"],
    desc: "Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.",
    story: [
      "Trà đào cam sả - Thức uống nhất định phải thử 1 lần khi đến The Coffee House",
      "Khi sáng chế ra thức uống này, Barista tại Nhà đã để lại dấu ấn riêng rất Việt trong món trà đào vốn đã quen thuộc đối với mọi người bằng một nguyên liệu rất đỗi dân dã - Sả, một loại cây vốn được trồng và sử dụng rộng rãi như là một gia vị thường thấy trong bữa ăn hằng ngày tại các nước châu Á. Sả có hương thơm của chanh, tính ấm, kết hợp với tính hàn của Cam vàng Mỹ, tạo nên sự kết hợp cân bằng, vừa mang dấu ấn riêng của Việt Nam, vừa có sự pha trộn phương Tây trong ly Trà đào Cam Sả The Coffee House. Vị thanh ngọt của đào Hy Lạp, vị chua dịu của Cam Vàng nguyên vỏ, vị chát của trà đen tươi được ủ mới mỗi 4 tiếng, cùng hương thơm nồng đặc trưng của sả chính là điểm sáng làm nên sức hấp dẫn của thức uống này.",
    ],
  },
];

export const coffee = [
  {
    id: 1,
    name: "Mocha Nóng",
    price: 59,
    salePrice: 35,
    img: "mocha-nong.jpg",
    cate: "coffee",
    size: ["Nhỏ", "Vừa"],
    desc: "Loại cà phê được tạo nên từ sự kết hợp hoàn hảo của vị đắng đậm đà của Espresso và sốt sô-cô-la ngọt ngào mang tới hương vị đầy lôi cuốn, đánh thức mọi giác quan nên đây chính là thức uống ưa thích của phụ nữ và giới trẻ.",
    story: [
      "Mocha - Một chút đắng của tình yêu đầu",
      "Không như cà phê Cappuchino chỉ có một lớp bọt sữa trên bề mặt, cà phê Mocha còn hòa quyện cả vị thơm béo của kem tươi và sốt sô-cô-la.Bên cạnh những loại cà phê máy như Espresso, Cappuchino, Latte,… thực khách tại Tê Coffee House cũng dành nhiều tình cảm cho một loại cà phê khác mang tên Mocha. Mocha là một dạng hỗn hợp giữa cà phê và sô-cô-la nóng. Không như cà phê Cappuchino chỉ có một lớp bọt sữa trên bề mặt, cà phê Mocha còn hòa quyện cả vị thơm béo của kem tươi và sốt sô-cô-la. Mùi vị này, hương thơm này tựa như hương vị của một tình yêu chớm nở, vừa có chút vị đắng của Espresso và sự ngọt ngào đầy lôi cuốn.",
    ],
  },
  {
    id: 2,
    name: "Latte Táo Lê Quế Đá",
    price: 58,
    salePrice: 40,
    img: "latte-tao-le-que-da.jpg",
    cate: "coffee",
    size: ["Vừa"],
    desc: "Sự kết hợp tuyệt vời giữa cà phê Espresso đậm đà, tinh tế với vị ngọt cay nhẹ của quế hòa quyện cùng vị chua ngọt dịu của táo lê, lớp foam bồng bềnh quyến rũ đã nên một thức uống độc đáo, tuyệt hảo cho những ngày se lạnh thêm ấp áp và trọn vẹn.",
    story: [
      "Cà phê Latte Táo Lê Quế - “Bản tình ca nhẹ nhàng” cho những ngày se lạnh",
      "Một món quà ấm áp mà The Coffee House đặc biệt dành tặng bạn cho mùa lễ hội năm nay. Một chút đắng nhẹ nhàng của Espresso hòa quyện vị trái cây thanh thoát, cay nhẹ nồng ấm của quế sẽ giúp bạn có những khoảnh khắc tuyệt vời vào những ngày cuối năm, cùng nhau nhìn lại một năm đã qua và bắt đầu một năm mới tràn ngập hạnh phúc.",
    ],
  },
  {
    id: 3,
    name: "Latte Táo Lê Quế Nóng",
    price: 58,
    salePrice: 40,
    img: "latte-tao-le-que-nong.jpg",
    cate: "coffee",
    size: ["Vừa"],
    desc: "Sự kết hợp tuyệt vời giữa cà phê Espresso đậm đà, tinh tế với vị ngọt cay nhẹ của quế hòa quyện cùng vị chua ngọt dịu của táo lê, lớp foam bồng bềnh quyến rũ đã nên một thức uống độc đáo, tuyệt hảo cho những ngày se lạnh thêm ấp áp và trọn vẹn.",
    story: [
      "Cà phê Latte Táo Lê Quế - “Bản tình ca nhẹ nhàng” của mùa đông",
      "Một món quà ấm áp mà The Coffee House đặc biệt dành tặng bạn cho mùa lễ hội năm nay. Một chút đắng nhẹ nhàng của Espresso hòa quyện vị trái cây thanh thoát, cay nhẹ nồng ấm của quế sẽ giúp bạn có những khoảnh khắc tuyệt vời vào những ngày cuối năm, cùng nhau nhìn lại một năm đã qua và bắt đầu một năm mới tràn ngập hạnh phúc.",
    ],
  },
  {
    id: 4,
    name: "Cappuchino Nóng",
    price: 49,
    salePrice: 34,
    img: "cappuccino.jpg",
    cate: "coffee",
    size: ["Nhỏ", "Vừa"],
    desc: "Cappuchino là thức uống hòa quyện giữa hương thơm của sữa, vị béo của bọt kem cùng vị đậm đà từ cà phê Espresso. Tất cả tạo nên một hương vị đặc biệt, nhẹ nhàng, trầm lắng và tinh tế.",
    story: [
      "Cappuchino - Hương vị hoàn hảo làm say đắm mọi giác quan",
      "Một điều nho nhỏ có lẽ bạn chưa biết, ở Ý, người ta thưởng thức một tách Cà phê Cappuccino chung với bữa sáng và hiếm khi uống Cappuccino sau 11 giờ trưa. Cappuchino là một thức uống quen thuộc gắn liền với đất nước Ý xinh đẹp và thơ mộng. Đây là một loại thức uống được pha chế cầu kỳ và tinh tế. Một tách Cappuchino ngon đúng điệu là sẽ mang hương vị nồng nàn của cà phê Espresso hòa quyện sữa thơm dịu, đi kèm lớp bọt sữa bồng bềnh, béo ngậy.",
    ],
  },
  {
    id: 5,
    name: "Espresso Nóng",
    price: 40,
    salePrice: 28,
    img: "espresso-nong.jpg",
    cate: "coffee",
    size: ["Nhỏ", "Vừa"],
    desc: "Một tách Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc.",
    story: [
      "Espresso - Cà phê tinh chất nhất theo phong cách Ý",
      "Tạm gác lại những ồn ào nơi phố thị và thử nhâm nhi ly cà phê Espresso hương vị đậm đà, tinh tế của The Coffee House để tận hưởng những khoảnh khắc diệu kỳ của cuộc sống. Người ta vẫn hay ví Espresso là phép màu trong một chiếc tách vì độ quyến rũ không phai của nó. Một cốc Espresso nguyên bản được bắt đầu bởi những hạt Arabica chất lượng, phối trộn với tỉ lệ cân đối hạt Robusta, cho ra vị ngọt caramel, vị chua dịu và sánh đặc. Để đạt được sự kết hợp này, The Coffee House xay tươi hạt cà phê cho mỗi lần pha.",
    ],
  },
];

export const iceBlended = [
  {
    id: 1,
    name: "Chocolate Đá Xay",
    price: 58,
    salePrice: 40,
    img: "chocolate-ice-blended.jpg",
    cate: "iceBlended",
    size: ["Vừa", "Lớn"],
    desc: "Sữa và kem tươi béo ngọt được “cá tính hoá” bởi vị chocolate/sô-cô-la đăng đắng. Dành cho các tín đồ hảo ngọt. Lựa chọn hàng đầu nếu bạn đang cần chút năng lượng tinh thần.",
    story: [
      "SÔ CÔ LA ĐÁ XAY - Thức uống cho tín đồ hảo ngọt",
      "Chocolate là một loại thực phẩm có nhiều công dụng hữu ích, làm hưng phấn tâm trạng do có caffeine, tyrosine và tryptophan. Trong các loại chocolate, chocolate đen được Barista Nhà dùng trong món chocolate đá xay có hàm lượng ca cao cao cùng với chất chống oxy hóa, ít chất béo nên có lợi cho sức khỏe hơn. Chỉ một lượng nhỏ chocolate cũng giúp bạn tràn đầy năng lượng",
    ],
  },
  {
    id: 2,
    name: "Đào Việt Quất Đá Xay",
    price: 58,
    salePrice: 40,
    img: "dao-viet-quat.jpg",
    cate: "iceBlended",
    size: ["Vừa", "Lớn"],
    desc: "Vị đào quen thuộc, được khoác lên mình dáng vẻ thanh mát hơn khi kết hợp với mứt berry và lớp kem ngọt béo ngậy, cho hương vị kích thích vị giác đầy lôi cuốn và khoan khoái ngay từ ngụm đầu tiên.",
    story: [
      "Đào Việt Quất Đá Xay - Sự Pha Trộn Hoàn Hảo Giữa Đào & Việt Quất",
      "Là phiên bản “upgrade” từ ly trà đào quen thuộc của nhà, tuy là “em út” trong giá đình đá xay nhưng món đào việt quất đá xay lại nhanh chóng quen mặt, sau thời gian thử thách đã chính thức từ thức uống theo mùa trở thành món uống trên menu chính thức của Nhà. Được khoác lên mình ngoại hình xịn sò, mang đến sự phấn khích và tươi mát ngay từ cái nhìn đầu tiên, ở giữa là vịđào huyền thoại ngọt thanh, lớp việt quất chua ngọt vui miệng ở tầng cuối, đặc biệt kéo theo lớp kem bồng bềnh béo ngậy trên cùng nữa mang đến hương vị kích thích vị giác đầy lôi cuốn và khoan khoái ngay từ ngụm đầu tiên.",
    ],
  },
  {
    id: 3,
    name: "Cookie Đá Xay",
    price: 58,
    salePrice: 40,
    img: "cookies-da-xay.jpg",
    cate: "iceBlended",
    size: ["Vừa", "Lớn"],
    desc: "Những mẩu bánh cookies giòn rụm kết hợp ăn ý với sữa tươi, kem tươi béo ngọt và đá xay mát lành, đem đến cảm giác lạ miệng gây thích thú và không thể cưỡng lại. Một món uống phá cách dễ thương đầy mê hoặc.",
    story: [
      "Cookie Đá Xay - Món uống phá cách dễ thương",
      "Nằm trong dòng thức uống đá xay (Ice Blended) quen thuộc của Nhà. Dòng thức uống kết hợp sữa tươi, đá viên với nhiều nguyên liệu khác. Đặc điểm “nhận dạng” dòng thức uống này chính là phần kem tươi xốp mịn bên trên. Cookie đá xay với những mẩu bánh cookies giòn rụm kết hợp ăn ý với sữa tươi, kem tươi béo ngọt và đá xay mát lành, đem đến cảm giác lạ miệng gây thích thú và không thể cưỡng lại. Một món uống phá cách dễ thương đầy mê hoặc",
    ],
  },
  {
    id: 4,
    name: "Sinh Tố Việt Quất",
    price: 58,
    salePrice: 40,
    img: "sinh-to-viet-quoc.jpg",
    cate: "iceBlended",
    size: ["Vừa"],
    desc: "Mứt Việt Quất chua thanh, ngòn ngọt, phối hợp nhịp nhàng với dòng sữa chua bổ dưỡng. Là món sinh tố thơm ngon mà cả đầu lưỡi và làn da đều thích.",
    story: [
      "Sinh tố Việt quất - Uống ngon, uống “đẹp”",
      "Sinh tố là tên gọi chung của những món trai cây xay. Ở Đây chúng ta có sinh tố việt quất với thành phần chính là mứt việt quất, sữa chua và Foam cheese. Mứt Việt Quất chua thanh, ngòn ngọt, phối hợp nhịp nhàng với dòng sữa chua bổ dưỡng, thêm vào đó là vị béo của Foam cheese được Barista Nhà phối hợp tinh tế. Tất cả tạo món sinh tố thơm ngon mà cả đầu lưỡi và làn da đều thích. ",
    ],
  },
  {
    id: 5,
    name: "Matcha Đá Xay",
    price: 58,
    salePrice: 40,
    img: "matcha-da-xay.jpg",
    cate: "iceBlended",
    size: ["Vừa", "Lớn"],
    desc: "Matcha thanh, nhẫn, và đắng nhẹ được nhân đôi sảng khoái khi uống lạnh. Nhấn nhá thêm những nét bùi béo của kem và sữa. Gây thương nhớ vô cùng!",
    story: [
      "Matcha Đá Xay - Thức uống gây thương nhớ vô cùng",
      "Matcha đá xay (còn gọi là trà xanh đá xay hay matcha ice blended) là thức uống được các Barista Nhà đưa vào menu ngay từ những ngày đầu. Mang đủ các đặc trưng của dòng đá xay, sự mát lạnh, lớp kem béo hấp dẫn, và cộng thêm hương vị matcha đặc biệt được tuyển chọn với chất lượng và hương vị hấp dẫn.  Matcha thanh, nhẫn, và đắng nhẹ được nhân đôi sảng khoái khi uống lạnh. Nhấn nhá thêm những nét bùi béo của kem và sữa. Dù không mới nhưng khả năng gây thương nhớ vẫn như những ngày đầu.",
    ],
  },
];

export const snack = [
  {
    id: 1,
    name: "Bánh Mì Que Pate Cay",
    price: 12,
    salePrice: 0,
    img: "banh-mi-que-pate.jpg",
    cate: "snack",
    desc: "Vỏ bánh mì giòn tan, kết hợp với lớp nhân pate béo béo đậm đà và 1 chút cay cay sẽ là lựa chọn lý tưởng nhẹ nhàng để lấp đầy chiếc bụng đói , cho 1 bữa sáng - trưa - chiều - tối của bạn thêm phần thú vị.",
    story: [
      "Bánh mì que Pate cay - Lựa chọn thú vị cho chiếc bụng đói",
      "Bánh mì que hay còn có tên gọi khác là bánh mì gậy) là một loại bánh mì Pháp xuất xứ từ nước Pháp (một số nguồn cho rằng loại bánh này có nguồn gốc nguyên thủy là ở vùng Torino của Ý). Có tên gọi như vậy chủ yếu là vì hình dạng thon dài của loại bánh này. Ở Việt Nam, bánh mì que lại nổi tiếng theo vùng, với mỗi vùng lại có hương vị đặc trưng riêng, nổi tiếng nhất là bánh mì que Hải Phòng & Đà Nẵng. Trong khi bánh mì que Hải Phòng thành phần chính là pate thì bánh mì que Đà Nẵng lại có thêm dăm bông, thịt nguội bên cạnh pate.",
    ],
  },
  {
    id: 2,
    name: "Chà Bông Phô Mai",
    price: 32,
    salePrice: 0,
    img: "cha-bong-pho-mai.jpg",
    cate: "snack",
    desc: "Chiếc bánh với lớp phô mai vàng sánh mịn bên trong, được bọc ngoài lớp vỏ xốp mềm thơm lừng. Thêm lớp chà bông mằn mặn hấp dẫn bên trên.",
    story: [
      "Bánh chà bông phô mai - Món bánh mặn không thể bỏ qua ở The Coffee House",
      "Là một biến tấu của bánh mì ngọt, bánh mì chà bông phô mai bắt đầu “hot” từ năm 2017. Phần bánh mì ngọt thơm sữa nhẹ truyền thống, được thêm vào lớp nhân phô mai tan chảy, phủ lên trên là chà bông mằn mặn cân bằng lại vị giác không đem đến cảm giác ngọt ngấy vốn có của các loại bánh ngọt có phô mai khác.",
    ],
  },
  {
    id: 3,
    name: "Croissant Trứng Muối",
    price: 32,
    salePrice: 0,
    img: "croissant-trung-muoi.jpg",
    cate: "snack",
    desc: "Croissant trứng muối thơm lừng, bên ngoài vỏ bánh giòn hấp dẫn bên trong trứng muối vị ngon khó cưỡng.",
    story: [
      "Croissant trứng muối - Bữa sáng năng lượng cho ngày dài",
      "Bữa sáng rất quan trọng nhưng dù thế nào cũng không được bỏ bữa bạn nhé! Để tiếp thêm năng lượng và sự tỉnh táo để bắt đầu một ngày làm việc thật hứng khởi, The Coffee House gợi ý bạn món Bánh Croissant trứng muối và mua kèm 1 Cà phê sữa đá.",
    ],
  },
  {
    id: 4,
    name: "Bánh Mì VN Thịt Nguội",
    price: 29,
    salePrice: 0,
    img: "banh-mi-vn-thit-nguoi.jpg",
    cate: "snack",
    desc: "Gói gọn trong ổ bánh mì Việt Nam, là từng lớp chả, từng lớp jambon hòa quyện cùng bơ và pate thơm lừng, thêm dưa rau cho bữa sáng đầy năng lượng.",
    story: [
      "Gói gọn trong ổ bánh mì Việt Nam, là từng lớp chả, từng lớp jambon hòa quyện cùng bơ và pate thơm lừng, thêm dưa rau cho bữa sáng đầy năng lượng.",
      "Gói gọn trong ổ bánh mì Việt Nam, là từng lớp chả, từng lớp jambon hòa quyện cùng bơ và pate thơm lừng, thêm dưa rau cho bữa sáng đầy năng lượng.",
    ],
  },
];

export const atHome = [
  {
    id: 1,
    name: "Cà phê sữa đá pack 6 lon",
    price: 83,
    salePrice: 0,
    img: "pack-ca-phe-sua-da.jpg",
    cate: "atHome",
    desc: "Với thiết kế lon cao trẻ trung, hiện đại và tiện lợi, Cà phê sữa đá lon thơm ngon đậm vị của The Coffee House sẽ đồng hành cùng nhịp sống sôi nổi của tuổi trẻ và giúp bạn có được một ngày làm việc đầy hứng khởi.",
    story: [
      "Cà phê sữa đá lon - Người bạn đồng hành của nhịp sống tuổi trẻ",
      "Bằng thiết kế lon cao trẻ trung, hiện đại và tiện lợi, dù ở đâu, bạn vẫn có thể tận hưởng vị cà phê sữa thơm ngon đến ngụm cuối cùng. Cà phê sữa đá lon The Coffee House là cà phê uống liền mang phong cách hiện đại, tiện dụng bắt kịp thị hiếu tiêu dùng của những người trẻ. Sản phẩm được sản xuất từ những hạt cà phê Việt thượng hạng",
    ],
  },
  {
    id: 2,
    name: "Cà Phê Rich Finish Gu Đậm Tinh Tế 350gr",
    price: 89,
    salePrice: 65,
    img: "ca-phe-rich-finish-dam.jpg",
    cate: "atHome",
    desc: "The Coffee House hiểu rằng ly cà phê ngon phải đậm đà, rõ vị từ cái chạm đầu tiên đến hậu vị vương vấn. Combo Cà phê Rich Finish sẽ mang đến những ly cà phê đậm, thơm, hương vị tinh tế với mức giá ưu đãi hấp dẫn giúp bạn bắt đầu ngày mới đầy năng lượng.",
    story: [
      "Rich Finish - Gu đậm tinh tế",
      `"Cá tính" rất riêng ấy được tạo nên bởi vùng thổ nhưỡng mà cây được vun trồng, bởi bàn tay người nông hộ đã thấu hiểu tường tận đất đai nơi này. Từng nốt hương mang vị mặn, đắng, chát, chua thanh hay ngọt ngào,... tất cả hoà quyện tạo thành những bản sắc khác biệt trong mỗi ngụm cà phê.`,
    ],
  },
  {
    id: 3,
    name: "Cà Phê Peak Flavor Hương Thơm Đỉnh Cao 350gr",
    price: 89,
    salePrice: 65,
    img: "ca-phe-peak-flavor.jpg",
    cate: "atHome",
    desc: "Được rang dưới nhiệt độ vàng, Cà phê Peak Flavor - Hương thơm đỉnh cao lưu giữ trọn vẹn hương thơm tinh tế đặc trưng của cà phê Robusta Đăk Nông và Arabica Cầu Đất. Với sự hòa trộn nhiều cung bậc giữa hương và vị sẽ mang đến cho bạn một ngày mới tràn đầy cảm hứng. Hương thơm nhiều cung bậc lan tỏa cho bạn đầy cảm hứng.",
    story: [
      "Cà phê rang xay Peak Flavor - Hương thơm đỉnh cao",
      "Bằng việc cho ra đời sản phẩm Cà phê Peak Flavor - Hương thơm đỉnh cao lưu giữ trọn vẹn hương thơm tinh tế đặc trưng của cà phê Robusta Đăk Nông và Arabica Cầu Đất. Với sự hòa trộn nhiều cung bậc giữa hương và vị sẽ mang đến cho bạn một ngày mới tràn đầy cảm hứng.",
    ],
  },
  {
    id: 4,
    name: "Cà Phê Arabica",
    price: 98,
    salePrice: 0,
    img: "ca-phe-arabica.jpg",
    cate: "atHome",
    desc: "The Coffee House gửi bạn hương vị cà phê từ 100% hạt Arabica, được chọn lọc kỹ lưỡng tại vùng Cầu Đất, với độ cao 1650m. Với vị đắng nhẹ, hậu vị chua thanh, ngọt dịu, Cà phê Arabica từ The Coffee House sẽ giúp bạn tạo ra những tách cà phê máy hay pha phin tinh tế yêu thích của riêng mình.",
    story: [
      "Điều gì làm nên hương vị nổi tiếng của cà phê rang xay Abrabica?",
      "Từ những cửa hàng đầu tiên, The Coffee House đã bắt đầu hợp tác với Cầu Đất Farm để trồng cà phê theo tiêu chuẩn riêng. Vùng đất phủ sương nằm ở độ cao 1.650m so với mặt nước biển này là nơi tốt nhất để trồng giống cà phê Arabica ở Việt Nam. Chính “độ cao vàng” ấy đã cho ra hạt cà phê Arabica thơm nhẹ, chua thanh tuyệt hảo. Nhắc đến Arabica, người ta thường nghĩ đến một trải nghiệm đặc biệt với sự chuyển biến trong cảm nhận của người thưởng thức: Vị chua thanh thấm dần vào khoang miệng sau đó kết thúc bằng vị ngọt trong trẻo.",
    ],
  },
];

export const all = coffee.concat(tea);
